### ISSUE TITLE
Bump NPM version to 1.0.7 for iOS support

### ISSUE THREAD

**Issue by ivar-tp** [praves77/cordova-plugin-android-idfa#11]
Hi,

Commits 46a2219dd5ae09c166216f52aa16a1f9983096ea & fed9b062dcecb208f3b4bb9826f813514fb6d4ef include iOS support but the public NPM package https://www.npmjs.com/package/cordova-plugin-android-idfa is tagged to the version 1.0.6 without these commits.

Can we bump the version in `package.json` to 1.0.7 to add iOS support on the npm installable version? This would be great!

Best,
Ivar

**Comment by praves77** [comment]
Merged
