### ISSUE TITLE
The version in NPM is outdated

### ISSUE THREAD

**Issue by sdurandeu** [praves77/cordova-plugin-android-idfa#2]
It would be ideal if you could update the package in [NPM](https://www.npmjs.com/package/cordova-plugin-android-idfa). For now, you can install using

```
cordova plugin add https://github.com/praves77/cordova-plugin-android-idfa.git
```

**Comment by zwacky** [comment]
fell for it again instead of adding the git url directly. 
please @praves77 bump the version on npm <3

**Comment by praves77** [comment]
Done. Let me know if you still have issue.
