### ISSUE TITLE
How do you access the AdId?

### ISSUE THREAD

**Issue by degaray** [praves77/cordova-plugin-android-idfa#3]
What do I need to call to get it?

**Comment by praves77** [comment]
getAdId(successCallback, errorCallback), after plugin has been registered/included in project and deviceReady.

**Comment by praves77** [comment]
ReadMe has details. Let me know if you need any other info/help.

**Comment by degaray** [comment]
yes, but if I run it globally the function will not exist. Which object do I need to use?

**Comment by vipulism** [comment]
@degaray : you can find the object with  name "androidIDFA" in the window object, after installing this plugin
