### ISSUE TITLE
How do I access the functions?

### ISSUE THREAD

**Issue by ikostadinov** [praves77/cordova-plugin-android-idfa#4]
Hey, I installed the plugin but I do not know which object to use to call the functions. I tried with injecting androidIDFA and link to the anfroidIDFA.js in the head but it always says it is undefined.

**Comment by peterholcomb** [comment]
@ikostadinov The documentation is pretty incomplete here.  The plugin attaches an 'androidIDFA' object to the window object.  So you'd use it like this:

window.androidIDFA.getAdInfo();
window.androidIDFA.getAdId();

**Comment by praves77** [comment]
Closing this. lmk if you need more info.
